version: "3.8"
services:
  anythink-backend:
    build: ./backend
    container_name: anythink-backend
    command: sh -c "cd backend && yarn install && /wait-for-it.sh mongodb:27017 -q -t 60 && yarn dev"

    environment:
      - NODE_ENV=development
      - PORT=3000
<<<<<<< HEAD
      - MONGODB_URI=mongodb://mongodb:27017
=======
      - MONGODB_URI=mongodb://mongodb-node:27017/anythink-market
>>>>>>> bbae1cbd0973251b11353c64298d93939133c69b
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/backend/node_modules
    ports:
      - "3000:3000"
    depends_on:
<<<<<<< HEAD
      - "mongodb"

  anythink-frontend:
    build: ./frontend
    container_name: anythink-frontend
=======
      - "mongodb-node"

  anythink-frontend-react:
    build: ./frontend
    container_name: anythink-frontend-react
>>>>>>> bbae1cbd0973251b11353c64298d93939133c69b
    command: sh -c "cd frontend && yarn install && yarn start"
    environment:
      - NODE_ENV=development
      - PORT=3001
    working_dir: /usr/src
    volumes:
      - ./:/usr/src/
      - /usr/src/frontend/node_modules
    ports:
      - "3001:3001"

<<<<<<< HEAD
  mongodb:
    container_name: mongodb
=======
  mongodb-node:
    container_name: mongodb-node
>>>>>>> bbae1cbd0973251b11353c64298d93939133c69b
    restart: always
    image: mongo
    logging:
      driver: none
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - '27017:27017'
